### ISSUE TITLE
rawurlencode(): Passing null to parameter #1 is deprecated

### ISSUE THREAD

**Issue by samwilson** [carlos-mg89/PHPoAuthLib#12]
A couple of deprecation warnings with PHP 8.3:

> Deprecated: rawurlencode(): Passing null to parameter 1 ($string) of type string is deprecated in carlos-mg89/oauth/src/OAuth/OAuth1/Signature/Signature.php on line 57

> Deprecated: rawurlencode(): Passing null to parameter 1 ($string) of type string is deprecated in carlos-mg89/oauth/src/OAuth/OAuth1/Service/AbstractService.php on line 225

**Comment by tacman** [comment]
Fixes in #13

**Comment by tacman** [comment]
Ooops, missed the one in 225
