### ISSUE TITLE
php 8.3: Deprecated: rawurlencode() Passing null to parameter #1

### ISSUE THREAD

**Issue by ZiTAL** [carlos-mg89/PHPoAuthLib#16]
Deprecated: rawurlencode(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/api/v1/vendor/flickr/phpflickr-cli/vendor/carlos-mg89/oauth/src/OAuth/OAuth1/Signature/Signature.php on line 57

**PHPoAuthLib/src/OAuth/OAuth1/Signature/Signature.php** line 57
```
            $signatureData[rawurlencode($key)] = rawurlencode($value ?? '');
```
I solved it changing this part of code, i don't know if this code it's ok for you, if you want i can do a pull request or you can change it by your own
```
$signatureData[rawurlencode((string)$key)] = rawurlencode((string)$value);
```

thank you

**Comment by samwilson** [comment]
This is a duplicate of #12, which has been fixed.

Are you using [0.8.16](https://packagist.org/packages/carlos-mg89/oauth#0.8.16)? It was only released a few days ago.

**Comment by ZiTAL** [comment]
```
            "name": "carlos-mg89/oauth",
            "version": "0.8.15",
```

I'm using another project that uses this one, but i see that you solved it, thank you!
